#!/bin/sh /etc/rc.common

START=91
STOP=11
USE_PROCD=1

start_service() 
{
        config_load tuya_esp_daemon
        procd_open_instance
        procd_set_param command /usr/bin/lua /usr/lib/openvpn-management-agent/main.lua
        procd_set_param respawn
        procd_close_instance
}
service_triggers() 
{
        procd_add_reload_trigger "openvpn-management-agent"
}
reload_service() 
{
        stop
        start
}